POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Paquito",
    "number": "646 200 152"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Pepico",
    "number": "646 200 152"
}